#!/bin/csh -f

set count=1
set date=`date +%Y%m%d`

set samedate=`grep ${date} res/values/strings.xml | wc -l `

set lastdate=`grep ${date} res/values/strings.xml | head -1 | cut -f1 -d. | sed -e 's/^.*>//' -e 's/^.* //'`
set lastcount=`grep ${date} res/values/strings.xml | head -1 | cut -f2 -d. | cut -f1 -d\<`
echo "Last date was ${date}.${lastcount}"

if ( ! -e libs/armeabi/libsmac.so ) then
  echo "ERROR: libsmac.so not built."
  exit 3
endif
if ( ! -e libs/armeabi/libinreachcorelib.so ) then
  echo "ERROR: libinreachcorelib.so is missing."
  exit 3
endif
if ( ! -e bin/survey-acquisition-management.apk ) then
  echo "ERROR: bin/survey-acquisition-management.apk is missing."
  exit 3
endif

echo cp bin/survey-acquisition-management.apk ~/Projects/succinctdata/succinct-data-${lastdate}.${lastcount}.apk
cp bin/survey-acquisition-management.apk ~/Projects/succinctdata/succinct-data-${lastdate}.${lastcount}.apk

echo "OK: New version saved as ~/Projects/succinctdata/succinct-data-${lastdate}.${lastcount}.apk"
