#!/bin/csh
rm -fr recipes stripped sd
mkdir -p stripped
mkdir -p recipes
mkdir -p sd
cd recipes
cp ../stats.dat .
foreach form ( ../forms/*.xhtml )
  echo $form
  ../../smac recipe xhcreate ${form}
end
foreach form ( ../forms/*.xml ) 
  echo $form
  ../../smac recipe create ${form}
end
cd ..

set count=1
foreach record ( records/*.xml )
  echo ../smac recipe strip ${record} stripped/${count}.stripped
  ../smac recipe strip  ${record} stripped/${count}.stripped
  echo ../smac recipe compress recipes stripped/${count}.stripped sd/${count}.sd
  ../smac recipe compress recipes stripped/${count}.stripped sd/${count}.sd
  echo ../smac recipe decompress recipes sd/${count}.sd stripped
  ../smac recipe decompress recipes sd/${count}.sd stripped
  @ count = $count + 1
end
